[package]
name = "backup-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
ssh2 = "0.9.4"
whoami = "1.4.1"
indicatif = "0.16.2"
rand = "0.8"
